// <auto-generated />
namespace App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Relation_Many_To_Many_MenuItemApplication_Role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Relation_Many_To_Many_MenuItemApplication_Role));
        
        string IMigrationMetadata.Id
        {
            get { return "201702161222477_Relation_Many_To_Many_MenuItemApplication_Role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
