// <auto-generated />
namespace App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Multilanguage_ManuItemApplication : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Multilanguage_ManuItemApplication));
        
        string IMigrationMetadata.Id
        {
            get { return "201702161234519_Multi-language_ManuItemApplication"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
