//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.MissionManagement.Resources.MissionOrder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MissionOrder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MissionOrder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Entities.MissionManagement.Resources.MissionOrder.MissionOrder", typeof(MissionOrder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new order mission.
        /// </summary>
        internal static string Add_order_mission {
            get {
                return ResourceManager.GetString("Add_order_mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Date.
        /// </summary>
        internal static string ArrivalDate {
            get {
                return ResourceManager.GetString("ArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arriving time.
        /// </summary>
        internal static string ArrivingTime {
            get {
                return ResourceManager.GetString("ArrivingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convocations.
        /// </summary>
        internal static string Convocations {
            get {
                return ResourceManager.GetString("Convocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date order.
        /// </summary>
        internal static string DateOrder {
            get {
                return ResourceManager.GetString("DateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure date.
        /// </summary>
        internal static string DepartureDate {
            get {
                return ResourceManager.GetString("DepartureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure time.
        /// </summary>
        internal static string DepartureTime {
            get {
                return ResourceManager.GetString("DepartureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Means of transport.
        /// </summary>
        internal static string Meansoftransport {
            get {
                return ResourceManager.GetString("Meansoftransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Means transport category.
        /// </summary>
        internal static string MeansTransportCategory {
            get {
                return ResourceManager.GetString("MeansTransportCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missions orders management.
        /// </summary>
        internal static string menu_title {
            get {
                return ResourceManager.GetString("menu_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission.
        /// </summary>
        internal static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order mission management.
        /// </summary>
        internal static string Order_management {
            get {
                return ResourceManager.GetString("Order_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number.
        /// </summary>
        internal static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missions orders.
        /// </summary>
        internal static string PluralName {
            get {
                return ResourceManager.GetString("PluralName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission order.
        /// </summary>
        internal static string SingularName {
            get {
                return ResourceManager.GetString("SingularName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation date.
        /// </summary>
        internal static string ValidationDate {
            get {
                return ResourceManager.GetString("ValidationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validations.
        /// </summary>
        internal static string Validations {
            get {
                return ResourceManager.GetString("Validations", resourceCulture);
            }
        }
    }
}
